# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-31 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='sample_passwd', max_length=100),
        ),
    ]
